gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG

springdoc:
  default-produces-media-type: application/json;charset=UTF-8

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true