spring:
  # MySQL Database 설정 (RDS)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:moci3d}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD}

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}  # 운영에서는 validate 또는 none 권장
    properties:
      hibernate:
        format_sql: true
        show_sql: false  # 운영에서는 false (성능 향상)
        use_sql_comments: true
        default_batch_fetch_size: 100

# ============================================
# 프로덕션 사이트 설정 (쿠키 도메인, URL)
# ============================================
custom:
  site:
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"

# ============================================
# 파일 저장 설정 (로컬 또는 S3)
# ============================================
file:
  storage:
    type: ${FILE_STORAGE_TYPE:local}  # local 또는 s3

# ============================================
# AWS S3 설정 (선택사항)
# ============================================
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME:}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
    stack:
      auto: false

# ============================================
# 로깅 설정
# ============================================
logging:
  level:
    root: INFO
    com.moci_3d_backend: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# ============================================
# Actuator 설정 (Health Check)
# ============================================
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always